dist: xenial
language: python
sudo: false

matrix:
  include:
    - python: 3.5
      install:
        - pip install "." pytest
      script:
        - mkdir tests/tmp
        - phmdoctest README.md --report --outfile tests/tmp/test_project_readme.py
        - pytest --strict -vv tests

    - python: 3.6
      install:
        &utest_install
        - pip install "." pytest
      script:
        &utest_run
        # These steps show how to use phmdoctest to generate
        # pytest files and reports.
        - mkdir tests/tmp
        # Run phmdoctest to generate test file and print the report.
        - phmdoctest tests/example1.md --report --outfile tests/tmp/test_example1.py
        - phmdoctest tests/example2.md --skip "Python 3.7" --skip LAST --report --outfile tests/tmp/test_example2.py
        # run the project test suite including the generated tests
        - pytest --strict -vv tests

        # These steps are specific to testing phmdoctest and are not
        # useful to developers using phmdoctest.
        # Check the generated test file against the expected file in doc folder
        - cmp doc/test_example1.py tests/tmp/test_example1.py
        - cmp doc/test_example2.py tests/tmp/test_example2.py
        # check the saved report against the expected file in doc folder
        - phmdoctest tests/example2.md --skip "Python 3.7" --skip LAST --report > tests/tmp/example2_report.txt
        - cmp doc/example2_report.txt tests/tmp/example2_report.txt

    - python: 3.7
      install: pip install tox coverage coveralls
      script: tox -e cover,inspect
      after_success:
        - coveralls

    - python: 3.8
      install: *utest_install
      script: *utest_run

    - python: pypy3.5
      install: *utest_install
      script: *utest_run

branches:
  only:
  - master
