ame: CI

# Note: The coverage job does not install phmdoctest.
#       It imports phmdoctest from the checked out
#       src folder via $PYTHONPATH.
#       The inspect job installs phmdoctest.
on:
  push:
  pull_request:
    branches: [develop]

jobs:
  pytest:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install "pytest>=5"
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # todo- replace 3 lines below with root/requirements.txt
        pip install "Click>=7.1.1"
        pip install "commonmark>=0.9.1"
        pip install "monotable>=2.1.1"
        pip freeze
    - name: Tests, coverage report
      run: |
        coverage run --branch --source=src -m pytest -vv tests
        coverage run --branch --source=src --append -m phmdoctest --help
        coverage report --show-missing
      env:
        PYTHONPATH: ${{ github.workspace }}/src

  inspect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # todo- replace 3 lines below with root/requirements.txt
        # pip install "Click>=7.1.1"
        # pip install "commonmark>=0.9.1"
        # pip install "monotable>=2.1.1"
        pip install "."
        pip install flake8
        pip install pep8-naming
        pip install mypy
        pip install typing
        pip install check-manifest
        pip install twine
        pip freeze
    - name: Code Style
      run: |
        flake8 --exit-zero --max-complexity=10
    - name: Type Hints
      run: |
        mypy src/phmdoctest --strict
        mypy tests/test_type_packaging.py --strict
      continue-on-error: true
    - name: Deployable
      run: |
        check-manifest
        python3 setup.py sdist
        twine check dist/*

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # This should be the same as in .readthedocs.yml
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r doc/requirements.txt
        pip freeze
    - name: Sphinx build
      run: |
        mkdir docbuild
        sphinx-build -b html -d docbuild/doctrees . docbuild/html

    - name: Upload docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docbuild/html
        retention-days: 5
