name: codecov.io
on:
  push:
    branches: [master]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install "pytest>=5"
        pip install codecov
        pip install -r requirements.txt
        pip freeze
    - name: codecov
      run: |
        coverage run --branch --source=src -m pytest -vv tests
        coverage run --branch --source=src --append -m phmdoctest --help
        codecov -X gcov
      env:
        PYTHONPATH: ${{ github.workspace }}/src
