name: codecov

# Note: The coverage job does not install phmdoctest.
#       It imports phmdoctest from the checked out
#       src folder via $PYTHONPATH.
on:
  push:
    branches: [master]

jobs:
  codecov:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install "pytest>=5"
        pip install codecov
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # todo- replace 3 lines below with root/requirements.txt
        pip install "Click>=7.1.1"
        pip install "commonmark>=0.9.1"
        pip install "monotable>=2.1.1"
        pip freeze
    - name: codecov
      run: |
        coverage run --branch --source=src -m pytest -vv tests
        coverage run --branch --source=src --append -m phmdoctest --help
        codecov -X gcov
      env:
        PYTHONPATH: ${{ github.workspace }}/src
